### ISSUE TITLE
optimize various extractions in recipe.py / update.py

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/manuscript-object#25]
From https://github.com/cu-mkp/m-k-manuscript-data/issues/1726

@gschare wrote:
>It was kinda painful to wait for the entire manuscript to regenerate every single time; maybe we should look into some form of caching, e.g. with Python Pickle or JSON for instances where we are testing functionality but not changing the original files?

Go forward with your thoughts and update here as you optimize

**Comment by gschare** [comment]
I used the standard Python JSON library to add an optional JSON save/load feature for the manuscript object. In update.py, you can tell it to save the manuscript object to a JSON (about 8 MB) which contains most of the information in each Recipe object. Then, next time you run update.py, you can tell it to load that JSON file, which speeds up generating the Recipe objects (the longest part of the generation process) from several minutes to a fraction of a second.

Clearly, the bottleneck in update.py was those few methods in the Recipe object: find_title(), find_categories(), clean_length(), and find_all_properties(). By storing the output of those computations in a JSON, any work to do with update.py that does not require regenerating the manuscript from original files (i.e. work to do with derivative files rather than original files) will be much more pleasant.

I will make a pull request for the changes.
